name: Nonprod deploy

on:
  push:
    branches:
      - main # target to stag (Sit) development testing
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      deploy_env:
        required: false # can target to other environemnt for individual development

jobs:
  initialize:
    uses: naluri-hidup/reusable-workflows/.github/workflows/.initialize.yml@v1.2
    secrets: inherit
    with:
      default_deploy_env: "stag"

  docker_build:
    needs: initialize
    uses: naluri-hidup/reusable-workflows/.github/workflows/.docker-build.yml@v1.2
    secrets: inherit
    with:
      git_branch: ${{ needs.initialize.outputs.git_branch }}
      deploy_env: ${{ needs.initialize.outputs.deploy_env }}
      git_sha_short: ${{ needs.initialize.outputs.git_sha_short }}
      ecr_name: "identity-provider"
      builder_cache: true

  ecs-deploy:
    needs: [initialize, docker_build]
    uses: naluri-hidup/reusable-workflows/.github/workflows/.ecs-deploy-task-definition.yml@v1.2
    secrets: inherit
    with:
      deploy_env: ${{ needs.initialize.outputs.deploy_env }}
      git_sha_short: ${{ needs.initialize.outputs.git_sha_short }}
      ecr_name: "identity-provider"
      git_branch: ${{ needs.initialize.outputs.git_branch }}
      reusable_tag: "v1.2"
