name: Workflow for nonprod deployment - initialization

on:
  workflow_call:
    secrets:
      SLACK_DEPLOYMENT_WEBHOOK:
        required: true
    inputs:
      deploy_env:
        required: false
        type: string
        default: 'staging'
    outputs:
      git_branch:
        value: ${{ jobs.initialize.outputs.git_branch }}
      git_sha_short: 
        value: ${{ jobs.initialize.outputs.git_sha_short }}
      deploy_env:
        value: ${{ jobs.initialize.outputs.deploy_env }}
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      git_branch: ${{ steps.set_git_var.outputs.git_branch }}
      git_sha_short: ${{ steps.set_git_var.outputs.git_sha_short }}
      deploy_env: ${{ steps.set_deploy_env.outputs.value }}
    steps:
      - name: Set git branch
        id: set_git_var
        shell: bash
        run: | 
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ $TAG == "refs/heads/"* ]]; then
            echo "git_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT 
            echo "git_sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT 
          else
            echo "git_branch=$(echo $TAG)" >> $GITHUB_OUTPUT
            echo "git_sha_short=$(echo $TAG)" >> $GITHUB_OUTPUT
          fi
          
      - name: Set deploy env
        id: set_deploy_env
        run: |
          DEPLOY_ENV=${{ github.event.inputs.deploy_env }}
          echo "value=${DEPLOY_ENV:-"staging"}" >> $GITHUB_OUTPUT 

      - name: Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":":rocket: [ *${{ github.repository }}* ] ${{ steps.set_git_var.outputs.git_branch }} source code branch to ${{ steps.set_deploy_env.outputs.value }} environment by *@${{ github.actor }}*: `started`"}' \
          ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}

