name: Workflow for move ecr image from one aws to another aws

on:
  workflow_call:
    secrets:
      STAG_GH_ACTIONS_ACCESS_KEY_ID:
        required: true
      STAG_GH_ACTIONS_SECRET_ACCESS_KEY:
        required: true
      PROD_GH_ACTIONS_ACCESS_KEY_ID:
        required: false
      PROD_GH_ACTIONS_SECRET_ACCESS_KEY:
        required: false
  inputs:
    git_sha_short:
      required: true
      type: string
    source_aws_account:
      required: false
      type: string
      default: 'stag'
    source_aws_region:
      required: false
      type: string
      default: 'ap-southeast-1'
    target_aws_account:
      required: false
      type
