name: Security Scan

on:
  workflow_call:
    secrets:
      SLACK_DEPLOYMENT_WEBHOOK:
        required: true
    inputs:
      disable-dast-scan:
        description: "Disable DAST scan"
        type: boolean
        required: false
        default: false
      dast-target:
        description: "DAST target URL"
        required: false
        type: string
        default: "https://naluri.life"

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    if: ${{ !inputs.disable-dast-scan }}
    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ inputs.dast-target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: "ZAP Baseline Scan Report"
