name: Workflow for terraform config changes

on:
  workflow_call:
    inputs:
      git_branch:
        required: true
        type: string
    outputs:
      terraform_config_changes:
        value: ${{ jobs.terraform-config-changes.outputs.files }}
      any_changed:
        value: ${{ jobs.terraform-config-changes.outputs.any_changed }}
jobs:
  terraform-config-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.terraform-config-changes.outputs.files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0

      - name: Git Pull
        run : git pull origin ${{ inputs.git_branch }}

      - name: Identify files changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/config/**
            **/**/config/**

      - name: List all changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        id: terraform-config-changes
        run: |
          JSON_files="["
          CHANGES=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" 
            JSON_line="\"$file\","
            JSON_files="$JSON_files$JSON_line"
            CHANGES=1
          done

          if [[ $CHANGES==1 ]]; then
            length=${#JSON_files}
            endIndex=$(expr $length - 1)
            JSON_files=${JSON_files:0:$endIndex}
          fi

          JSON_files="$JSON_files]"

          echo "$JSON_files"
          echo "files=$(echo "$JSON_files")" >> $GITHUB_OUTPUT