name: Workflow for terraform

on:
  workflow_call:
    secrets:
      TERRAFORM_ACCESS_KEY_ID:
        required: true
      TERRAFORM_SECRET_ACCESS_KEY:
        required: true
      TERRAFORM_REGION:
        required: true
      SLACK_DEPLOYMENT_WEBHOOK:
        required: true
    inputs:
      config_path:
        required: true
        type: string
      git_branch:
        required: true
        type: string
      apply:
        required: false
        type: boolean
        default: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0

      - name: Git Pull
        run : git pull origin ${{ inputs.git_branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TERRAFORM_REGION }}
      
      - name: Get Module & Config
        run : |
          config_path=${{ inputs.config_path }}
          IFS="/config/" read -a arr <<< $config_path
          echo $arr[0] # module

          IFS="/" read -a arr1 <<< $arr[1]
          IFS=".tfvars" read -a arr1 <<< $arr1[${#arr1[@]} - 1]

          echo $arr1[0] # config

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      
      # - name: Terraform Init
      #   run: cd ${{ inputs.module_name }} && make CONFIG_NAME=${{ inputs.config_name }} terraform.init

      # - name: Terraform Plan
      #   run: cd ${{ inputs.module_name }} && make CONFIG_NAME=${{ inputs.config_name }} terraform.plan

      # - name: Terrraform Apply
      #   if: ${{ inputs.apply }}
      #   run: cd ${{ inputs.module_name }} && make CONFIG_NAME=${{ inputs.config_name }} terraform.apply