name: Nonprod deploy

on:
  push:
    branches:
      - main # target to staging
  workflow_dispatch:
    inputs:
      deploy_env:
        required: false
        default: "staging"

jobs:
  nonprod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: naluri-hidup/reusable-workflow/.github/workflows/.init-nonprod-deploy.yml

      - name: ECS deployment
        uses: aluri-hidup/reusable-workflow/.github/workflows/.ecs-nonprod-deploy.yml
      
        

