name: Nonprod deploy

on:
  push:
    branches:
      - main # target to staging
  workflow_dispatch:
    inputs:
      deploy_env:
        required: false
        default: "staging"

jobs:
  init:
    uses: naluri-hidup/reusable-workflow/.github/workflows/.init-nonprod-deploy.yml@main

  ecs-deploy:
    uses: aluri-hidup/reusable-workflow/.github/workflows/.ecs-nonprod-deploy.yml@main
      
        

